name: simple_permissions
description: A new flutter plugin project.
version: 0.1.11
author: Ethras
homepage: https://github.com/Ethras/flutter_simple_permissions

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

flutter:
  plugin:
    androidPackage: com.ethras.simplepermissions
    pluginClass: SimplePermissionsPlugin

